# Funding options for NXTG-Forge
# GitHub will display these options in the repository sidebar

# GitHub Sponsors
# github: [nxtg-ai]

# Other funding platforms
# patreon: nxtg-forge
# open_collective: nxtg-forge
# ko_fi: nxtgforge
# custom: ['https://nxtg.ai/sponsor']

# Note: Uncomment and update the above lines when funding options are available
