name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! We appreciate your ideas to improve NXTG-Forge.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it here.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to have...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also considered...

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of NXTG-Forge does this feature relate to?
      options:
        - Agent System
        - CLI Interface
        - State Management
        - Template Generation
        - MCP Integration
        - Testing
        - Documentation
        - Infrastructure/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (significant impact)
        - Medium (would be nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: I would use this feature to...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: |
        Examples from other tools:
        - Tool X does this by...
        - Reference: https://...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: I have reviewed the project roadmap to see if this is already planned
          required: true
        - label: I am willing to help implement this feature (optional)
          required: false
