/**
 * Init Service Templates
 * All template strings for agents and CLAUDE.md generation
 */

import type { ProjectType } from "./types";

/**
 * Agent template definitions
 */
export const AGENT_TEMPLATES = {
  general: `---
name: starter-general
description: Universal development assistant for any project type
tools: ["Glob", "Grep", "Read", "Write", "Edit", "Bash"]
---

# Starter Agent - General Purpose

You are a helpful development assistant. Follow project conventions and maintain code quality.

## Capabilities
- Code review and suggestions
- Bug fixing and debugging
- Documentation writing
- Test creation
- General development tasks

## Guidelines
- Read existing code before making changes
- Follow the project's coding style
- Write tests for new functionality
- Keep changes focused and minimal
`,

  react: `---
name: starter-react
description: React 19 specialist with hooks and modern patterns
tools: ["Glob", "Grep", "Read", "Write", "Edit", "Bash"]
---

# Starter Agent - React

You are a React specialist. Use modern React 19 patterns with hooks and functional components.

## Capabilities
- React component development
- State management with hooks
- Performance optimization
- Testing with Vitest/React Testing Library

## Guidelines
- Prefer functional components with hooks
- Use TypeScript for type safety
- Follow React best practices
- Write accessible components
`,

  node: `---
name: starter-node
description: Node.js/Express backend specialist
tools: ["Glob", "Grep", "Read", "Write", "Edit", "Bash"]
---

# Starter Agent - Node.js

You are a Node.js backend specialist. Build scalable, secure APIs.

## Capabilities
- REST API development
- Database integration
- Authentication/Authorization
- Testing with Jest/Vitest

## Guidelines
- Use async/await patterns
- Implement proper error handling
- Follow security best practices
- Write comprehensive tests
`,

  python: `---
name: starter-python
description: Python/FastAPI backend specialist
tools: ["Glob", "Grep", "Read", "Write", "Edit", "Bash"]
---

# Starter Agent - Python

You are a Python specialist. Build clean, well-tested applications.

## Capabilities
- FastAPI/Flask development
- Database integration with SQLAlchemy
- Type hints and validation
- Testing with pytest

## Guidelines
- Use type hints throughout
- Follow PEP 8 style guidelines
- Write comprehensive tests
- Use virtual environments
`,

  fullstack: `---
name: starter-fullstack
description: Full-stack development combining frontend and backend
tools: ["Glob", "Grep", "Read", "Write", "Edit", "Bash"]
---

# Starter Agent - Full Stack

You are a full-stack specialist. Bridge frontend and backend seamlessly.

## Capabilities
- End-to-end feature development
- API design and integration
- Database modeling
- Testing across the stack

## Guidelines
- Maintain consistency between frontend/backend
- Design clean API contracts
- Write integration tests
- Consider security at all layers
`,
} as const;

/**
 * Generate config.yml content
 */
export function generateConfig(projectType: ProjectType): string {
  return `# NXTG-Forge Configuration
# Generated by /frg-init wizard

project:
  type: ${projectType}
  initialized: ${new Date().toISOString()}

agents:
  enabled: true
  auto_assign: true

memory:
  enabled: true
  retention_days: 90

quality:
  min_coverage: 85
  strict_types: true
  linting: strict
`;
}

/**
 * Generate complete CLAUDE.md
 */
export function generateCompleteClaude(
  vision: string,
  projectType: ProjectType,
): string {
  return `# Project Knowledge Base

## Vision

${vision}

## Project Type

${projectType}

## Development Guidelines

### Code Quality
- Maintain 85%+ test coverage
- Use strict TypeScript/type checking
- Follow SOLID principles
- Write self-documenting code

### Testing
- Write tests before implementation (TDD)
- Cover happy path, edge cases, and errors
- Use meaningful test descriptions

### Documentation
- Document public APIs and interfaces
- Keep README up to date
- Use JSDoc/docstrings for complex logic

---

${generateForgeSection(vision, projectType)}
`;
}

/**
 * Generate NXTG-Forge section for CLAUDE.md
 */
export function generateForgeSection(
  vision: string,
  projectType: ProjectType,
): string {
  return `## NXTG-Forge Integration

This project is enhanced with NXTG-Forge - an AI-orchestrated development system.

### What is NXTG-Forge?

NXTG-Forge is your AI Chief of Staff that:
- Plans and tracks feature development
- Maintains code quality and architecture
- Provides intelligent recommendations
- Automates repetitive tasks
- Ensures project governance

### Project Vision

${vision}

### Available Commands

- \`/frg-status\` - View project status and health
- \`/frg-feature "name"\` - Plan and implement a new feature
- \`/frg-test\` - Run comprehensive test suite
- \`/frg-deploy\` - Deploy application
- \`/frg-checkpoint\` - Create project checkpoint
- \`/frg-report\` - Generate session report

### Project Configuration

- **Type**: ${projectType}
- **Forge Version**: 3.0.0
- **Initialized**: ${new Date().toISOString()}

### Directory Structure

\`\`\`
.claude/
  forge/
    config.yml          # Forge configuration
    agents/             # Starter agents for this project type
    memory/             # Session and context memory
  governance.json       # Project governance and tracking
  plans/                # Feature plans and designs
  skills/               # Project-specific knowledge
\`\`\`

### Next Steps

1. Run \`/frg-status\` to see current project state
2. Use \`/frg-feature "feature name"\` to plan your first feature
3. Let NXTG-Forge guide you through implementation

---

*Generated by NXTG-Forge v3.0.0*
`;
}
